# Generated by Django 2.1.7 on 2019-04-16 20:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('rur', 'RUR'), ('usd', 'USD'), ('eur', 'EUR')], default='rur', max_length=3)),
                ('account_no', models.IntegerField(default=1000000)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.CharField(max_length=255)),
                ('transaction_dttm', models.DateTimeField(default=datetime.datetime(2019, 4, 16, 20, 36, 40, 256909))),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='mybank.Account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='mybank.Account')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('join_dt', models.DateField(default=datetime.date(2019, 4, 16))),
                ('quit_dt', models.DateField(default=datetime.date(2099, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mybank.User')),
                ('access_level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
            ],
            bases=('mybank.user',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mybank.User')),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mybank.Account')),
            ],
            bases=('mybank.user',),
        ),
    ]
