# Generated by Django 2.1.7 on 2019-04-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_dttm',
            new_name='t_dttm',
        ),
    ]
