# Generated by Django 2.1.7 on 2019-04-16 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0002_auto_20190416_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_dttm',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 20, 48, 53, 589751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_dt',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 20, 48, 53, 588488, tzinfo=utc)),
        ),
    ]
