# Generated by Django 2.1.7 on 2019-04-16 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0003_auto_20190416_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_dttm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_dt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
