# Generated by Django 2.1.7 on 2019-04-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0004_auto_20190421_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_sent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
